export const icons = {
  add: require("@/assets/icons/add.png"),
  likes: require("@/assets/icons/likes.png"),
  more: require("@/assets/icons/more.png"),
  search: require("@/assets/icons/search.png"),
  notifications: require("@/assets/icons/notifications.png"),
  verified: require("@/assets/icons/verified.png"),
  views: require("@/assets/icons/views.png"),
  videos: require("@/assets/icons/videos.png"),
  messages: require("@/assets/icons/messages.png"),
  blogs: require("@/assets/icons/blogs.png"),
  add_circle: require("@/assets/icons/add_circle.png"),
  comments: require("@/assets/icons/comment.png"),
  appreciate: require("@/assets/icons/appreciate.png"),
  checked: require("@/assets/icons/checked.png"),
  check_box: require("@/assets/icons/check_box.png"),
};
